### ISSUE TITLE
Plex Guide Empty

### ISSUE THREAD

**Issue by cjtodaro** [tmurphy605/PlexTVChannel#5]
I made it through all the steps, added Xteve to Plex, but the guide is showing empty. I'm running an Ubuntu VM on Windows 10.

**Comment by pythcon** [comment]
Let me see your xmltv.xml file and the variables you have set in your generatePlaylist.py file.

**Comment by cjtodaro** [comment]
Hey-

I'm self teaching python and Linux as I go with this, so let me know if I did anything dumb.

Here are the variables as set in the playlist script:
cartoons = ["Rick and Morty", "Bob's Burgers", "South Park"]

dir = "/home/chris/shared/TV/" # Directory to grab shows from (make sure there is a "/" at the end!)
tvDirectory = "/home/chris/PlexTV/tvDIR/" # Directory where files will be generated (make sure there is a "/" at the end!)
commercialsDirectory = "" # Directory where commercials will be pulled from (make sure there is a "/" at the end!)
timezone = "EST" # Enter Timezone
showPoster = ""
channelName = ""





Here is the XMLTV file that was generated by the generateXMLTV.py script:

<tv generator-info-name='Todd' source-info-name='Todds Generator'>
<channel id='1'>
<display-name></display-name>
<icon src=''/>
</channel>
<programme channel='1' start='20200429103000 EST' stop='20200429105206 EST'>
<title lang='en'>Rick and Morty</title>
<desc lang='en'>Rick and Morty - S03E08 - Morty's Mind Blowers Bluray-1080p ||

 An animated series that follows the misadventures of an alcoholic scientist Rick and his overly nervous grandson Morty, who split their time between domestic family life and intergalactic travel. Often finding themselves in a heap of trouble that more often than not is created through their own actions.</desc>
<icon height='' src='http://thetvdb.com/banners/posters/275274-2.jpg' width=''/>
<video/>
<date/>
<new/>
</programme>
<programme channel='1' start='20200429105206 EST' stop='20200429111443 EST'>
<title lang='en'>Rick and Morty</title>
<desc lang='en'>Rick and Morty - S04E03 - One Crew Over the Crewcoo's Morty WEBDL-1080p ||

 An animated series that follows the misadventures of an alcoholic scientist Rick and his overly nervous grandson Morty, who split their time between domestic family life and intergalactic travel. Often finding themselves in a heap of trouble that more often than not is created through their own actions.</desc>
<icon height='' src='http://thetvdb.com/banners/posters/275274-2.jpg' width=''/>
<video/>
<date/>
<new/>
</programme>
<programme channel='1' start='20200429111443 EST' stop='20200429113622 EST'>
<title lang='en'>Bob's Burgers</title>
<desc lang='en'>Bob's Burgers - S10E18 - Tappy Tappy Tappy Tap Tap Tap WEBDL-1080p ||

 Bob's Burgers follows a third-generation restaurateur, Bob, as he runs Bob's Burgers with the help of his wife and their three kids. Bob and his quirky family have big ideas about burgers, but fall short on service and sophistication. Despite the greasy counters, lousy location and a dearth of customers, Bob and his family are determined to make Bob's Burgers "grand re-re-re-opening" a success.</desc>
<icon height='' src='http://thetvdb.com/banners/posters/194031-2.jpg' width=''/>
<video/>
<date/>
<new/>
</programme>
<programme channel='1' start='20200429113622 EST' stop='20200429115800 EST'>
<title lang='en'>Bob's Burgers</title>
<desc lang='en'>Bob's Burgers - S10E15 - Yurty Rotten Scoundrels WEBDL-1080p ||

 Bob's Burgers follows a third-generation restaurateur, Bob, as he runs Bob's Burgers with the help of his wife and their three kids. Bob and his quirky family have big ideas about burgers, but fall short on service and sophistication. Despite the greasy counters, lousy location and a dearth of customers, Bob and his family are determined to make Bob's Burgers "grand re-re-re-opening" a success.</desc>
<icon height='' src='http://thetvdb.com/banners/posters/194031-2.jpg' width=''/>
<video/>
<date/>
<new/>
</programme>
<programme channel='1' start='20200429115800 EST' stop='20200429122028 EST'>
<title lang='en'>South Park</title>
<desc lang='en'>South Park - S23E06 - Season Finale WEBDL-1080p ||

 South Park is an animated series featuring four boys who live in the Colorado town of South Park, which is beset by frequent odd occurrences. The show grew out of a short film that Trey Parker and Matt Stone created called The Spirit of Christmas, and has become an award-winning show that is a unique blend of humor and satire.</desc>
<icon height='' src='http://thetvdb.com/banners/posters/75897-5.jpg' width=''/>
<video/>
<date/>
<new/>
</programme>
<programme channel='1' start='20200429122028 EST' stop='20200429124256 EST'>
<title lang='en'>South Park</title>
<desc lang='en'>South Park - S23E09 - Basic Cable WEBDL-1080p ||

 South Park is an animated series featuring four boys who live in the Colorado town of South Park, which is beset by frequent odd occurrences. The show grew out of a short film that Trey Parker and Matt Stone created called The Spirit of Christmas, and has become an award-winning show that is a unique blend of humor and satire.</desc>
<icon height='' src='http://thetvdb.com/banners/posters/75897-5.jpg' width=''/>
<video/>
<date/>
<new/>
</programme>
</tv>

**Comment by cjtodaro** [comment]
Hey-

I'm learning python and Linux as I go with this project, so please let me know if I did anything dumb.

Here's the variables in the generatePlaylist.py script:

`cartoons = ["Rick and Morty", "Bob's Burgers", "South Park"]

dir = "/home/chris/shared/TV/" # Directory to grab shows from (make sure there is a "/" at the end!)
tvDirectory = "/home/chris/PlexTV/tvDIR/" # Directory where files will be generated (make sure there is a "/" at the end!)
commercialsDirectory = "" # Directory where commercials will be pulled from (make sure there is a "/" at the end!)
timezone = "EST" # Enter Timezone
showPoster = ""
channelName = ""
`


[xmltv1.zip](https://github.com/tmurphy605/PlexTVChannel/files/4553950/xmltv1.zip)

**Comment by pythcon** [comment]
Your timezone is incorrect. The timezone should be in the format "+/- 0000" so for EST I use "-0400". Try that and refresh your guide inside Plex.

**Comment by cjtodaro** [comment]
Hmmmm...still didn't work. 

I have your scripts and Xteve running in the VM, plex itself is running on windows. Would that be creating an issue?

**Comment by pythcon** [comment]
Are you able to add the dvr into live tv? You probably won't be able to because it's not on the same instance. Settings>TV&DVR>Add DVR

**Comment by cjtodaro** [comment]
That I can do. I can insert the DVR, it'll see my one "Cartoons" Channel, I load in the XMLTV file the script created, and then it takes me to the normal DVR page for the guide, but says "The Guide is Empty". I've also tried setting it up using the XTEVE XMLTV address that shows at the top of the XTEVE page - same thing.

**Comment by pythcon** [comment]
Did you ever get this working?
